version: 2

workflows:
  version: 2
  build:
    jobs:
      - build-node8
      - build-node10
      - build-node12
jobs:
  build-node8: &base
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get install -y bluetooth bluez libbluetooth-dev libudev-dev
      - run: yarn install
      - run: yarn test
  build-node10:
    <<: *base
    docker:
      - image: circleci/node:10
  build-node12:
    <<: *base
    docker:
      - image: circleci/node:12
